out = ['Output:Speed limit (50km/h)',
 'Output:Yield',
 'Output:Speed limit (70km/h)',
 'Output:Priority road',
 'Output:Yield',
 'Output:Speed limit (80km/h)',
 'Output:Right-of-way at intersection',
 'Output:Dangerous curve right ',
 'Output:Keep right',
 'Output:Yield',
 'Output:Yield',
 "Output:Dangerous curve left\x7fI'm a big fan of the Dixie Dixie Dixie",
 'Output:Road work ',
 'Output:No passing veh over 3.5 tons',
 'Output:Bumpy road',
 'Output:No passing',
 'Output:Pedestrians',
 'Output:Speed limit (60km/h)',
 'Output:Speed limit (50km/h)',
 'Output:Road work \n\nRoad work\n\nRoad work\n\n',
 'Output:Road work \n\nRoad work\n\nRoad work\n\n',
 'Output:Children crossing ',
 'Output:Speed limit (100km/h)',
 'Output:Yield',
 'Output:Speed limit (80km/h)']

import re 
